<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdScanner.Domain\IdScanner.Domain.csproj" />
    <ProjectReference Include="..\IdScanner.UI.Application\IdScanner.UI.Application.csproj" />
    <ProjectReference Include="..\IdScanner.UI.Domain\IdScanner.UI.Domain.csproj" />
    <ProjectReference Include="..\IdScanner.UI.Infrastructure\IdScanner.UI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
